-- ARQUIVO LEGADO DESATIVADO.
-- O script anterior recriava um trigger inseguro que aceitava role dos metadados.
-- Não execute correções avulsas sobre o banco.
-- Consulte ../RELEASE_CHECKLIST.md e migrations/202610010001_production_foundation.sql.
-- Nenhuma alteração é executada por este arquivo.
